apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-app-test
spec:
  template: 
    spec:
      containers:
      - image: my-image
        name: my-app
        securityContext:
          allowPrivilegeEscalation: true
          runAsUser: 0
